clockor2/phylojs

docs/cite.md, docs/index.md, docs/install.md, docs/reader.md, docs/tree.md, docs/writer.md, mkdocs.yml
A branch on which to update documentation. For not, is has a structure for docs (API ref + examples) that we will fill out later by adding doc strings etc.
=> Documentation

tsconfig.json
Remove "test/**/*.ts" from tsconfig - it's already remove from the build
=> Update tsconfig.json to remove tests

docs/examples/midpoint.md, docs/examples/reroot.md, docs/examples/test/rttr.spec.ts, mkdocs.yml
Added some examples to documentation for rerooting and rttr
=> :memo: adding documentation examples

docs/examples/reroot.md, docs/examples/test/rttr.spec.ts, docs/examples/vis.html
Fix examples tests  import bug. Updated example.
=> :bug: fix text and update reroot example

.eslintignore, package-lock.json, package.json, tsconfig.json, webpack.config.js
Add webpack to create a minified bundle for CDN
=> build: add webpack

docs/examples/test/rttr.spec.ts
=> fix(example-tests): compatible with webpack build

docs/examples/annotations.md, docs/examples/index.md, docs/examples/test/rttr.spec.ts, docs/examples/vis.html, docs/examples/visualise.html, docs/examples/visualise.md, docs/examples/writer.md, mkdocs.yml, src/Write.ts
`writeNewick()` now writes annotations. Along with this, I have added a new example on manipulating annotations following suggestion from @sebastianduchene .
=> fix(writeNewick() annotations): plus new example

docs/examples/test/examples.spec.ts, docs/examples/treeArray.md, src/io/readers/neXML.ts, src/io/readers/newick.ts, src/io/readers/nexus.ts, src/io/readers/phyloXML.ts, src/io/readers/tree.ts, src/tree/tree.ts
Added examples for reading trees.
=> fix: add examples for reading trees

mkdocs.yml
fix documentation nav for example
=> fix: update examples nav

.eslintignore, src/io/readers/neXML.ts, src/io/readers/newick.ts, src/io/readers/nexus.ts, src/io/readers/phyloXML.ts, src/io/readers/tree.ts, src/io/writers/newick.ts, src/io/writers/nexus.ts, test/io/readers.spec.ts, test/io/writers.spec.ts, test/tree/node.spec.ts, test/tree/tree.spec.ts, tsconfig.json
Reverted back to relative imports as they were breaking the bundler
=> Relative imports

docs/examples/treeArray.md
=> more small typo fixes

src/index.ts, src/io/readers/phyJSON.ts, src/io/readers/tree.ts, test/io/readers.spec.ts
=> :sparkles: phyJSON reader

src/io/readers/tree.ts
=> :bug: add phyJSON to Schema

.husky/prepare-commit-msg
=> feat: add cz back to pre-commit

src/index.ts
Added annotation writers to exports.
=> fix: expose annotation writers

src/io/readers/newick.ts, test/io/readers.spec.ts
=> fix: fix multi tree read newick bug

src/tree/node.ts
cartoon and collapsed removed form Node class
=> fix: remove old node node vis properties

src/tree/node.ts, test/tree/node.spec.ts
Post-order traversal method on Node class. Comes with two tests including one to calculate node ages.
re  #65
=> feat: add `Node.applyPostOrder` method and tests

package-lock.json
=> fix: update package-lock.json for security audit

.github/workflows/release.yml
=> fix(release): Increase node space in release.yml

package.json
There's an issue with coverage so I've disabled it for now.
=> Remove coverage so tests will run
